### ISSUE TITLE
Python deps won't install

### ISSUE THREAD

**Issue by bugs181** [jvilk/mitmproxy-node#5]
`$ npm install --save mitmproxy`
```
> mitmproxy@2.1.0 postinstall /Users/levi/Desktop/.../mitmproxy
> scripts/install_python_deps.py

['version:']
Traceback (most recent call last):
  File "scripts/install_python_deps.py", line 17, in <module>
    version[0] = int(version[0])
ValueError: invalid literal for int() with base 10: 'version:'
npm WARN debugging@1.0.0 No description
npm WARN debugging@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mitmproxy@2.1.0 postinstall script.
```

Log file:
```
112 verbose stack Error: mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`
112 verbose stack Exit status 1
112 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
112 verbose stack     at EventEmitter.emit (events.js:182:13)
112 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
112 verbose stack     at ChildProcess.emit (events.js:182:13)
112 verbose stack     at maybeClose (internal/child_process.js:962:16)
112 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
113 verbose pkgid mitmproxy@2.1.0
114 verbose cwd /Users/Levi/...
115 verbose Darwin 18.0.0
116 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "mitmproxy"
117 verbose node v11.0.0
118 verbose npm  v6.4.1
119 error code ELIFECYCLE
120 error errno 1
121 error mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`
121 error Exit status 1
122 error Failed at the mitmproxy@2.1.0 postinstall script.
122 error This is probably not a problem with npm. There is likely additional logging output above.
123 verbose exit [ 1, true ]
```

`$ python3 scripts/install_python_deps.py`
```
['version:']
Traceback (most recent call last):
  File "scripts/install_python_deps.py", line 17, in <module>
    version[0] = int(version[0])
ValueError: invalid literal for int() with base 10: 'version:'
```

`$ mitmproxy --version`
```
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Darwin-18.0.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.14 ('', '', '') x86_64
```

`$ python3 -V`
```
Python 3.7.1
```

`$ node -v`
```
v11.0.0
```

`$ npm -v`
```
6.4.1
```

**Comment by Jonahss** [comment]
Readme says you need mitmproxy version 4.
